export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const COMPANY_LIST = "COMPANY_LIST";
export const COMPANY_ADD = "COMPANY_ADD";
export const COMPANY_EDIT = "COMPANY_EDIT";
export const COMPANY_DELETE = "COMPANY_DELETE";

